const birdsActionTypes = {
  FETCH_INFO_START: "FETCH_INFO_START",
  FETCH_INFO_SUCCESS: "FETCH_INFO_SUCCESS",
  FETCH_INFO_FAIL: "FETCH_INFO_FAIL",
  SET_CURRENT_BIRD_ARRAY: "SET_CURRENT_BIRD_ARRAY",
};

export default birdsActionTypes;
