const birdsActionTypes = {
  FETCH_INFO_START: "FETCH_INFO_START",
  FETCH_INFO_SUCCESS: "FETCH_INFO_SUCCESS",
  FETCH_INFO_FAIL: "FETCH_INFO_FAIL",
  SET_CURRENT_BIRD_ARRAY: "SET_CURRENT_BIRD_ARRAY",
  SET_RANDOM_VALUE: "SET_RANDOM_VALUE",
  SET_ACTIVE_BIRD: "SET_ACTIVE_BIRD",
  SET_QUESTION_BIRD: "SET_QUESTION_BIRD",
  SET_ANSWERED: "SET_ANSWERED",
  INCREASE_SCORE: "INCREASE_SCORE",
  INCREASE_LEVEL: "INCREASE_LEVEL",
  DECREASE_EXPTRA_SCORE: "DECREASE_EXPTRA_SCORE",
  RESET_EXTRA_SCORE: "RESET_EXTRA_SCORE",
  RESET_ACTIVE_BIRD: "RESET_ACTIVE_BIRD",
  RESET_GAME: "RESET_GAME",
  FILL_COLORS_ARRAY: "FILL_COLORS_ARRAY",
  CHANGE_LIST_COLOR: "CHANGE_LIST_COLOR",
};

export default birdsActionTypes;
