const birdsActionTypes = {
  FETCH_IMAGE_START: "FETCH_IMAGE_START",
  FETCH_IMAGE_SUCCESS: "FETCH_IMAGE_SUCCESS",
  FETCH_IMAGE_FAILURE: "FETCH_IMAGE_FAILURE",
  FETCH_SONG_START: "FETCH_SONG_START",
  FETCH_SONG_SUCCESS: "FETCH_SONG_SUCCESS",
  FETCH_SONG_FAILURE: "FETCH_SONG_FAILURE",
  CHOOSE_CURRENT_LIST: "CHOOSE_CURRENT_LIST",
  GO_NEXT_LEVEL_START: "GO_NEXT_LEVEL_START",
  GO_NEXT_LEVEL_SUCCESS: "GO_NEXT_LEVEL_SUCCESS",
  GO_NEXT_LEVEL_FAILURE: "GO_NEXT_LEVEL_FAILURE",
};

export default birdsActionTypes;
