const userActionTypes = {
  SIGN_UP_START: "SIGN_UP_START",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAIL: "SIGN_UP_FAIL",
  LOGIN_START: "LOGIN_START",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT: "LOGOUT",
  UPDATE_LEVEL_START: "UPDATE_LEVEL_START",
  UPDATE_LEVEL_SUCCESS: "UPDATE_LEVEL_SUCCESS",
  UPDATE_LEVEL_FAIL: "UPDATE_LEVEL_FAIL",
};

export default userActionTypes;
